/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/workspaces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 워크스페이스 생성
         * @description 워크스페이스 생성
         */
        post: operations["workspace-create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 로그인
         * @description 이메일/비밀번호로 로그인합니다
         */
        post: operations["auth-login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 로그아웃
         * @description 리프레시 토큰을 해지합니다
         */
        post: operations["auth-logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 토큰 갱신
         * @description 리프레시 토큰으로 새 토큰을 발급받습니다
         */
        post: operations["auth-refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/signup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 회원가입
         * @description 이메일/비밀번호로 회원가입합니다
         */
        post: operations["auth-signup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/problems/ingest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 문제 등록
         * @description 크롤러에서 수집한 백준 문제를 등록합니다
         */
        post: operations["problem-ingest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/problems/{problemId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 문제 조회
         * @description 문제 ID로 문제를 조회합니다
         */
        get: operations["problem-get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 내 정보 조회
         * @description 로그인한 사용자의 정보를 조회합니다
         */
        get: operations["user-get-me"];
        put?: never;
        post?: never;
        /**
         * 회원 탈퇴
         * @description 로그인한 사용자의 계정을 삭제합니다
         */
        delete: operations["user-delete-me"];
        options?: never;
        head?: never;
        /**
         * 내 정보 수정
         * @description 로그인한 사용자의 정보를 수정합니다
         */
        patch: operations["user-update-me"];
        trace?: never;
    };
    "/api/v1/workspaces/explore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 워크스페이스 탐색 목록 조회
         * @description 워크스페이스 탐색 페이지에서 목록을 조회합니다
         */
        get: operations["workspace-explore"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 내 워크스페이스 목록 조회
         * @description 유저가 속한 워크스페이스 목록을 조회합니다 (/me)
         */
        get: operations["workspace-my-list-me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspaceId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 워크스페이스 상세 조회
         * @description 워크스페이스 상세 조회
         */
        get: operations["workspace-get"];
        put?: never;
        post?: never;
        /**
         * 워크스페이스 삭제
         * @description 워크스페이스를 삭제합니다
         */
        delete: operations["workspace-delete"];
        options?: never;
        head?: never;
        /**
         * 워크스페이스 수정
         * @description 워크스페이스 정보를 수정합니다
         */
        patch: operations["workspace-update"];
        trace?: never;
    };
    "/api/v1/problems/number/{problemNumber}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 문제 번호로 조회
         * @description 백준 문제 번호로 문제를 조회합니다
         */
        get: operations["problem-get-by-number"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspaceId}/boards": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 게시글 목록 조회
         * @description 워크스페이스 게시글 목록을 조회합니다
         */
        get: operations["board-list"];
        put?: never;
        /**
         * 게시글 생성
         * @description 게시글을 생성합니다
         */
        post: operations["board-create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspaceId}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 워크스페이스 멤버 목록 조회
         * @description 워크스페이스 멤버 목록 조회
         */
        get: operations["workspace-members"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspaceId}/problem-boxes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 문제집 목록 조회
         * @description 워크스페이스의 문제집 목록을 페이징 조회합니다
         */
        get: operations["problem-box-list"];
        put?: never;
        /**
         * 문제집 생성
         * @description 문제집 생성
         */
        post: operations["problem-box-create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspaceId}/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 워크스페이스 설정 조회
         * @description 워크스페이스 설정 조회
         */
        get: operations["workspace-settings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/me/profile-image/presigned-url": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 프로필 이미지 업로드 Presigned URL 생성
         * @description S3에 프로필 이미지를 업로드하기 위한 Presigned URL을 생성합니다. JPEG, PNG, WEBP만 허용되며 최대 5MB입니다.
         */
        post: operations["user-create-profile-image-presigned-url"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspaceId}/boards/{boardId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 게시글 상세 조회
         * @description 게시글 상세 정보를 조회합니다
         */
        get: operations["board-get"];
        put?: never;
        post?: never;
        /**
         * 게시글 삭제
         * @description 게시글을 삭제합니다
         */
        delete: operations["board-delete"];
        options?: never;
        head?: never;
        /**
         * 게시글 수정
         * @description 게시글을 수정합니다
         */
        patch: operations["board-update"];
        trace?: never;
    };
    "/api/v1/workspaces/{workspaceId}/members/invite": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 워크스페이스 멤버 초대
         * @description 워크스페이스 멤버 초대
         */
        post: operations["workspace-invite"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspaceId}/members/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 워크스페이스 멤버 조회
         * @description 워크스페이스 멤버 조회
         */
        get: operations["workspace-member-me"];
        put?: never;
        post?: never;
        /**
         * 워크스페이스 탈퇴
         * @description 워크스페이스 탈퇴
         */
        delete: operations["workspace-leave"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspaceId}/members/{workspaceMemberId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * 워크스페이스 멤버 추방
         * @description 워크스페이스 멤버 추방
         */
        delete: operations["workspace-member-remove"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspaceId}/problem-boxes/{problemBoxId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 문제집 단건 조회
         * @description 문제집 상세 정보를 조회합니다
         */
        get: operations["problem-box-get"];
        put?: never;
        post?: never;
        /**
         * 문제집 삭제
         * @description 문제집을 삭제합니다 (OWNER/MANAGER 전용)
         */
        delete: operations["problem-box-delete"];
        options?: never;
        head?: never;
        /**
         * 문제집 수정
         * @description 문제집 제목/설명을 수정합니다 (OWNER/MANAGER 전용)
         */
        patch: operations["problem-box-update"];
        trace?: never;
    };
    "/api/v1/workspaces/{workspaceId}/boards/{boardId}/comments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 게시글 댓글 목록 조회
         * @description 게시글 댓글 목록을 조회합니다
         */
        get: operations["board-comment-list"];
        put?: never;
        /**
         * 게시글 댓글 생성
         * @description 게시글 댓글을 생성합니다
         */
        post: operations["board-comment-create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspaceId}/boards/{boardId}/likes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 게시글 좋아요 상태 조회
         * @description 좋아요 수와 내 좋아요 여부를 조회합니다
         */
        get: operations["board-like-status"];
        /**
         * 게시글 좋아요 등록
         * @description 게시글에 좋아요를 등록합니다
         */
        put: operations["board-like"];
        post?: never;
        /**
         * 게시글 좋아요 취소
         * @description 게시글 좋아요를 취소합니다
         */
        delete: operations["board-unlike"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspaceId}/boards/{boardId}/pin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * 게시글 고정 상태 변경
         * @description 게시글의 고정 상태를 변경합니다
         */
        patch: operations["board-pin"];
        trace?: never;
    };
    "/api/v1/workspaces/{workspaceId}/members/me/nickname": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * 워크스페이스 닉네임 수정
         * @description 워크스페이스 닉네임 수정
         */
        patch: operations["workspace-member-nickname-update"];
        trace?: never;
    };
    "/api/v1/workspaces/{workspaceId}/members/{workspaceMemberId}/role": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * 워크스페이스 멤버 권한 변경
         * @description 워크스페이스 멤버 권한을 변경합니다
         */
        patch: operations["workspace-member-role-update"];
        trace?: never;
    };
    "/api/v1/workspaces/{workspaceId}/boards/{boardId}/comments/{commentId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * 게시글 댓글 삭제
         * @description 게시글 댓글을 삭제합니다
         */
        delete: operations["board-comment-delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ProblemDetail-Forbidden */
        "ProblemDetail-Forbidden": {
            /** @description 예외 클래스명 */
            exception: string;
            /** @description 오류 인스턴스 */
            instance?: string | null;
            /** @description 오류 상세 메시지 */
            detail: string;
            /** @description 에러 코드 */
            title: string;
            /** @description 오류 문서 URI */
            type: string;
            /** @description 발생 시각 */
            timestamp: string;
            /** @description HTTP 상태 코드 */
            status: number;
        };
        /** ProfileImageUploadRequest */
        ProfileImageUploadRequest: {
            /** @description 파일 크기 (바이트, 최대 5MB) */
            fileSize: number;
            /** @description 이미지 Content-Type (image/jpeg, image/png, image/webp) */
            contentType: string;
        };
        /** RefreshRequest */
        RefreshRequest: {
            /** @description 리프레시 토큰 */
            refreshToken: string;
        };
        /** CreateCommentRequest */
        CreateCommentRequest: {
            /** @description 댓글 내용 */
            content: string;
        };
        /** UpdateWorkspaceMemberRoleRequest */
        UpdateWorkspaceMemberRoleRequest: {
            /** @description 변경할 권한 */
            role: string;
        };
        /** ApiResponse-WorkspaceSettings */
        "ApiResponse-WorkspaceSettings": {
            /** @description 응답 데이터 */
            data: {
                /** @description MM 웹훅 URL */
                mmWebhookUrl?: string | null;
                /** @description 워크스페이스 이름 */
                name: string;
                /** @description 워크스페이스 설명 */
                description?: string | null;
                /** @description 워크스페이스 ID */
                id: number;
            };
            /** @description 성공 여부 */
            success: boolean;
            /** @description 메시지 */
            message?: string | null;
        };
        /** ApiResponse-BoardLikeStatus */
        "ApiResponse-BoardLikeStatus": {
            /** @description 응답 데이터 */
            data: {
                /** @description 좋아요 수 */
                likeCount: number;
                /** @description 내 좋아요 여부 */
                myLike: boolean;
            };
            /** @description 성공 여부 */
            success: boolean;
            /** @description 메시지 */
            message?: string | null;
        };
        /** ApiResponse-AuthTokenResponse */
        "ApiResponse-AuthTokenResponse": {
            /** @description 응답 데이터 */
            data: {
                /** @description 새 액세스 토큰 */
                accessToken: string;
                /** @description 새 리프레시 토큰 */
                refreshToken: string;
            };
            /** @description 성공 여부 */
            success: boolean;
            /** @description 메시지 */
            message?: string | null;
        };
        /** ApiResponse-UserResponse */
        "ApiResponse-UserResponse": {
            /** @description 응답 데이터 */
            data: {
                /** @description 인증 제공자 (GOOGLE, KAKAO, LOCAL) */
                provider: string;
                /** @description 이름 */
                name: string;
                /** @description 백준 아이디 */
                baekjoonId?: string | null;
                /** @description 유저 ID */
                id: number;
                /** @description 프로필 이미지 URL */
                profileImageUrl?: string | null;
                /** @description 이메일 */
                email: string;
            };
            /** @description 성공 여부 */
            success: boolean;
            /** @description 메시지 */
            message?: string | null;
        };
        /** ApiResponse-BoardList */
        "ApiResponse-BoardList": {
            /** @description 응답 데이터 */
            data: Record<string, never>;
            /** @description 성공 여부 */
            success: boolean;
            /** @description 메시지 */
            message?: string | null;
        };
        /** UpdateBoardRequest */
        UpdateBoardRequest: {
            /** @description 고정 여부 */
            pinned?: boolean | null;
            /** @description 제목 */
            title?: string | null;
            /** @description 게시글 타입 */
            type?: string | null;
            /** @description 내용 */
            content?: string | null;
        };
        /** CreateWorkspaceRequest */
        CreateWorkspaceRequest: {
            /** @description 워크스페이스 이름 */
            name: string;
            /** @description 워크스페이스 설명 */
            description?: string | null;
        };
        /** ProblemDetail-NotFound */
        "ProblemDetail-NotFound": {
            /** @description 예외 클래스명 */
            exception: string;
            /** @description 오류 인스턴스 */
            instance?: string | null;
            /** @description 오류 상세 메시지 */
            detail: string;
            /** @description 에러 코드 */
            title: string;
            /** @description 오류 문서 URI */
            type: string;
            /** @description 발생 시각 */
            timestamp: string;
            /** @description HTTP 상태 코드 */
            status: number;
        };
        /** SignupRequest */
        SignupRequest: {
            /** @description 비밀번호 */
            password: string;
            /** @description 이름 */
            name: string;
            /** @description 이메일 */
            email: string;
        };
        /** ApiResponse-Void */
        "ApiResponse-Void": {
            /** @description 성공 여부 */
            success: boolean;
            /** @description 메시지 */
            message?: string | null;
        };
        /** PinBoardRequest */
        PinBoardRequest: {
            /** @description 고정 여부 */
            pinned: boolean;
        };
        /** ProblemDetail-Validation */
        "ProblemDetail-Validation": {
            /** @description 예외 클래스명 */
            exception: string;
            /** @description 필드 오류 목록 */
            fieldErrors: {
                /** @description 필드명 */
                field: string;
                /** @description 오류 메시지 */
                message: string;
                /** @description 거절된 값 */
                rejectedValue?: Record<string, never> | null;
            }[];
            /** @description 오류 인스턴스 */
            instance?: string | null;
            /** @description 오류 상세 메시지 */
            detail: string;
            /** @description 에러 코드 */
            title: string;
            /** @description 오류 문서 URI */
            type: string;
            /** @description 발생 시각 */
            timestamp: string;
            /** @description HTTP 상태 코드 */
            status: number;
        };
        /** LoginRequest */
        LoginRequest: {
            /** @description 비밀번호 */
            password: string;
            /** @description 이메일 */
            email: string;
        };
        /** CreateProblemBoxRequest */
        CreateProblemBoxRequest: {
            /** @description 문제집 설명 */
            description?: string | null;
            /** @description 문제집 제목 */
            title: string;
        };
        /** UpdateWorkspaceMemberNicknameRequest */
        UpdateWorkspaceMemberNicknameRequest: {
            /** @description 닉네임 */
            nickname: string;
        };
        /** ApiResponse-ProblemBoxList */
        "ApiResponse-ProblemBoxList": {
            /** @description 응답 데이터 */
            data: {
                /** @description 페이지 정보 */
                page: {
                    /** @description 마지막 페이지 여부 */
                    last: boolean;
                    /** @description 페이지 크기 */
                    size: number;
                    /** @description 전체 페이지 수 */
                    totalPages: number;
                    /** @description 페이지 번호 */
                    page: number;
                    /** @description 첫 페이지 여부 */
                    first: boolean;
                    /** @description 전체 요소 수 */
                    totalElements: number;
                };
                /** @description 문제집 목록 */
                content: {
                    /** @description 생성일 */
                    createdAt: string;
                    /** @description 문제집 ID */
                    id: number;
                    /** @description 문제집 제목 */
                    title: string;
                    /** @description 최근 수정일 */
                    updatedAt: string;
                }[];
            };
            /** @description 성공 여부 */
            success: boolean;
            /** @description 메시지 */
            message?: string | null;
        };
        /** ApiResponse-WorkspaceExplore */
        "ApiResponse-WorkspaceExplore": {
            /** @description 응답 데이터 */
            data: {
                /** @description 페이지 정보 */
                page: {
                    /** @description 마지막 페이지 여부 */
                    last: boolean;
                    /** @description 페이지 크기 */
                    size: number;
                    /** @description 전체 페이지 수 */
                    totalPages: number;
                    /** @description 페이지 번호 */
                    page: number;
                    /** @description 첫 페이지 여부 */
                    first: boolean;
                    /** @description 전체 요소 수 */
                    totalElements: number;
                };
                /** @description 워크스페이스 목록 */
                content: {
                    /** @description 워크스페이스 이름 */
                    name: string;
                    /** @description 워크스페이스 설명 */
                    description?: string | null;
                    /** @description 워크스페이스 ID */
                    id: number;
                }[];
            };
            /** @description 성공 여부 */
            success: boolean;
            /** @description 메시지 */
            message?: string | null;
        };
        /** ApiResponse-BoardDetail */
        "ApiResponse-BoardDetail": {
            /** @description 응답 데이터 */
            data: Record<string, never>;
            /** @description 성공 여부 */
            success: boolean;
            /** @description 메시지 */
            message?: string | null;
        };
        /** UpdateProblemBoxRequest */
        UpdateProblemBoxRequest: {
            /** @description 문제집 설명 */
            description?: string | null;
            /** @description 문제집 제목 */
            title: string;
        };
        /** ApiResponse-WorkspaceMemberResponse */
        "ApiResponse-WorkspaceMemberResponse": {
            /** @description 응답 데이터 */
            data: {
                /** @description 권한 */
                role: string;
                /** @description 닉네임 */
                nickname: string;
                /** @description 워크스페이스 멤버 ID */
                workspaceMemberId: number;
            };
            /** @description 성공 여부 */
            success: boolean;
            /** @description 메시지 */
            message?: string | null;
        };
        /** InviteWorkspaceMemberRequest */
        InviteWorkspaceMemberRequest: {
            /** @description 초대할 이메일 */
            email: string;
        };
        /** ApiResponse-WorkspaceMemberList */
        "ApiResponse-WorkspaceMemberList": {
            /** @description 응답 데이터 */
            data: {
                /** @description 멤버 목록 */
                items: {
                    /** @description 권한 */
                    role: string;
                    /** @description 닉네임 */
                    nickname: string;
                    /** @description 워크스페이스 멤버 ID */
                    workspaceMemberId: number;
                }[];
            };
            /** @description 성공 여부 */
            success: boolean;
            /** @description 메시지 */
            message?: string | null;
        };
        /** UpdateWorkspaceRequest */
        UpdateWorkspaceRequest: {
            /** @description MM 웹훅 URL */
            mmWebhookUrl?: string | null;
            /** @description 워크스페이스 이름 */
            name?: string | null;
            /** @description 워크스페이스 설명 */
            description?: string | null;
        };
        /** ApiResponse-WorkspaceMyPage */
        "ApiResponse-WorkspaceMyPage": {
            /** @description 응답 데이터 */
            data: {
                /** @description 페이지 정보 */
                page: {
                    /** @description 마지막 페이지 여부 */
                    last: boolean;
                    /** @description 페이지 크기 */
                    size: number;
                    /** @description 전체 페이지 수 */
                    totalPages: number;
                    /** @description 페이지 번호 */
                    page: number;
                    /** @description 첫 페이지 여부 */
                    first: boolean;
                    /** @description 전체 요소 수 */
                    totalElements: number;
                };
                /** @description 워크스페이스 목록 */
                content: {
                    /** @description 워크스페이스 이름 */
                    name: string;
                    /** @description 워크스페이스 설명 */
                    description?: string | null;
                    /** @description 워크스페이스 ID */
                    id: number;
                }[];
            };
            /** @description 성공 여부 */
            success: boolean;
            /** @description 메시지 */
            message?: string | null;
        };
        /** ApiResponse-CommentList */
        "ApiResponse-CommentList": {
            /** @description 응답 데이터 */
            data: Record<string, never>;
            /** @description 성공 여부 */
            success: boolean;
            /** @description 메시지 */
            message?: string | null;
        };
        /** ProblemDetail-InvalidParameter */
        "ProblemDetail-InvalidParameter": {
            /** @description 예외 클래스명 */
            exception: string;
            /** @description 오류 인스턴스 */
            instance?: string | null;
            /** @description 오류 상세 메시지 */
            detail: string;
            /** @description 에러 코드 */
            title: string;
            /** @description 오류 문서 URI */
            type: string;
            /** @description 발생 시각 */
            timestamp: string;
            /** @description HTTP 상태 코드 */
            status: number;
        };
        /** ApiResponse-PresignedUrlResponse */
        "ApiResponse-PresignedUrlResponse": {
            /** @description 응답 데이터 */
            data: {
                /** @description 업로드 완료 후 이미지 접근 URL */
                imageUrl: string;
                /** @description S3 업로드용 Presigned URL */
                presignedUrl: string;
            };
            /** @description 성공 여부 */
            success: boolean;
            /** @description 메시지 */
            message?: string | null;
        };
        /** ApiResponse-WorkspaceResponse */
        "ApiResponse-WorkspaceResponse": {
            /** @description 응답 데이터 */
            data: {
                /** @description 워크스페이스 이름 */
                name: string;
                /** @description 워크스페이스 설명 */
                description?: string | null;
                /** @description 워크스페이스 ID */
                id: number;
            };
            /** @description 성공 여부 */
            success: boolean;
            /** @description 메시지 */
            message?: string | null;
        };
        /** ApiResponse-ProblemBoxResponse */
        "ApiResponse-ProblemBoxResponse": {
            /** @description 응답 데이터 */
            data: {
                /** @description 생성일 */
                createdAt: string;
                /** @description 문제집 설명 */
                description?: string | null;
                /** @description 문제집 ID */
                id: number;
                /** @description 문제집 제목 */
                title: string;
            };
            /** @description 성공 여부 */
            success: boolean;
            /** @description 메시지 */
            message?: string | null;
        };
        /** ApiResponse-Comment */
        "ApiResponse-Comment": {
            /** @description 응답 데이터 */
            data: Record<string, never>;
            /** @description 성공 여부 */
            success: boolean;
            /** @description 메시지 */
            message?: string | null;
        };
        /** CreateBoardRequest */
        CreateBoardRequest: {
            /** @description 고정 여부 */
            pinned?: boolean | null;
            /** @description 제목 */
            title: string;
            /** @description 게시글 타입 */
            type: string;
            /** @description 내용 */
            content: string;
        };
        /** ApiResponse-ProblemResponse */
        "ApiResponse-ProblemResponse": {
            /** @description 응답 데이터 */
            data: {
                /** @description 시간 제한 */
                timeLimit?: string | null;
                /** @description 입력 설명 */
                inputDescription?: string | null;
                /** @description 알고리즘 태그 목록 */
                algorithmTags: {
                    /** @description 태그 이름 */
                    name: string;
                    /** @description 태그 ID */
                    id: number;
                }[];
                /** @description 난이도 */
                tier?: string | null;
                /** @description 백준 문제 번호 */
                problemNumber: number;
                /** @description 문제 설명 */
                description?: string | null;
                /** @description 메모리 제한 */
                memoryLimit?: string | null;
                /** @description 문제 ID */
                id: number;
                /** @description 문제 제목 */
                title: string;
                /** @description 출력 설명 */
                outputDescription?: string | null;
                /** @description 입출력 예제 목록 */
                samples: {
                    /** @description 예제 출력 */
                    output?: string | null;
                    /** @description 예제 입력 */
                    input?: string | null;
                    /** @description 예제 번호 */
                    sampleIndex: number;
                    /** @description 예제 ID */
                    id: number;
                }[];
                /** @description 백준 문제 URL */
                url?: string | null;
            };
            /** @description 성공 여부 */
            success: boolean;
            /** @description 메시지 */
            message?: string | null;
        };
        /** ProblemIngestRequest */
        ProblemIngestRequest: {
            /** @description 시간 제한 */
            timeLimit?: string | null;
            /** @description 난이도 */
            tier?: string | null;
            /** @description 출력 설명 */
            problemOutput?: string | null;
            /** @description 메모리 제한 */
            memoryLimit?: string | null;
            /** @description 백준 문제 번호 */
            problemNum: number;
            /** @description 입력 설명 */
            problemInput?: string | null;
            /** @description 문제 설명 */
            problemDesc?: string | null;
            /** @description 문제 제목 */
            title: string;
            /** @description 입출력 예제 목록 */
            samples?: {
                /** @description 예제 출력 */
                output?: string | null;
                /** @description 예제 입력 */
                input?: string | null;
                /** @description 예제 번호 */
                sampleIndex: number;
            }[];
            /** @description 백준 문제 URL */
            url?: string | null;
            /** @description 알고리즘 태그 목록 */
            tags?: {
                /** @description 태그 이름 */
                name: string;
            }[];
        };
        /** UserUpdateRequest */
        UserUpdateRequest: {
            /** @description 수정할 이름 (30자 이내) */
            name?: string | null;
            /** @description 백준 아이디 */
            baekjoonId?: string | null;
            /** @description 수정할 프로필 이미지 URL */
            profileImageUrl?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    "workspace-create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json;charset=UTF-8": components["schemas"]["CreateWorkspaceRequest"];
            };
        };
        responses: {
            /** @description 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse-WorkspaceResponse"];
                };
            };
            /** @description 400 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail-Validation"];
                };
            };
        };
    };
    "auth-login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json;charset=UTF-8": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse-AuthTokenResponse"];
                };
            };
        };
    };
    "auth-logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json;charset=UTF-8": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse-Void"];
                };
            };
        };
    };
    "auth-refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json;charset=UTF-8": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse-AuthTokenResponse"];
                };
            };
        };
    };
    "auth-signup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json;charset=UTF-8": components["schemas"]["SignupRequest"];
            };
        };
        responses: {
            /** @description 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse-AuthTokenResponse"];
                };
            };
        };
    };
    "problem-ingest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json;charset=UTF-8": components["schemas"]["ProblemIngestRequest"];
            };
        };
        responses: {
            /** @description 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse-ProblemResponse"];
                };
            };
        };
    };
    "problem-get": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 문제 ID */
                problemId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse-ProblemResponse"];
                };
            };
        };
    };
    "user-get-me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse-UserResponse"];
                };
            };
        };
    };
    "user-delete-me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse-Void"];
                };
            };
        };
    };
    "user-update-me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json;charset=UTF-8": components["schemas"]["UserUpdateRequest"];
            };
        };
        responses: {
            /** @description 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse-UserResponse"];
                };
            };
        };
    };
    "workspace-explore": {
        parameters: {
            query?: {
                /** @description 검색어 */
                name?: string;
                /** @description 페이지 번호 */
                page?: string;
                /** @description 페이지 크기 */
                size?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse-WorkspaceExplore"];
                };
            };
            /** @description 400 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail-InvalidParameter"];
                };
            };
        };
    };
    "workspace-my-list-me": {
        parameters: {
            query?: {
                /** @description 페이지 번호 */
                page?: string;
                /** @description 페이지 크기 */
                size?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse-WorkspaceMyPage"];
                };
            };
        };
    };
    "workspace-get": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 워크스페이스 ID */
                workspaceId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse-WorkspaceResponse"];
                };
            };
            /** @description 404 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail-NotFound"];
                };
            };
        };
    };
    "workspace-delete": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 워크스페이스 ID */
                workspaceId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse-Void"];
                };
            };
            /** @description 403 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail-Forbidden"];
                };
            };
        };
    };
    "workspace-update": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 워크스페이스 ID */
                workspaceId: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json;charset=UTF-8": components["schemas"]["UpdateWorkspaceRequest"];
            };
        };
        responses: {
            /** @description 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse-WorkspaceResponse"];
                };
            };
            /** @description 400 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail-Validation"];
                };
            };
        };
    };
    "problem-get-by-number": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 백준 문제 번호 */
                problemNumber: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse-ProblemResponse"];
                };
            };
        };
    };
    "board-list": {
        parameters: {
            query?: {
                /** @description 게시글 타입 */
                type?: string;
                /** @description 검색어 */
                keyword?: string;
                /** @description 페이지 */
                page?: string;
                /** @description 크기 */
                size?: string;
                /** @description 정렬 */
                sort?: string;
                /** @description 고정글 우선 정렬 */
                pinnedFirst?: string;
            };
            header?: never;
            path: {
                /** @description 워크스페이스 ID */
                workspaceId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse-BoardList"];
                };
            };
        };
    };
    "board-create": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 워크스페이스 ID */
                workspaceId: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json;charset=UTF-8": components["schemas"]["CreateBoardRequest"];
            };
        };
        responses: {
            /** @description 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse-BoardDetail"];
                };
            };
        };
    };
    "workspace-members": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 워크스페이스 ID */
                workspaceId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse-WorkspaceMemberList"];
                };
            };
            /** @description 403 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail-Forbidden"];
                };
            };
        };
    };
    "problem-box-list": {
        parameters: {
            query?: {
                /** @description 페이지 번호 */
                page?: string;
                /** @description 페이지 크기 */
                size?: string;
            };
            header?: never;
            path: {
                /** @description 워크스페이스 ID */
                workspaceId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse-ProblemBoxList"];
                };
            };
            /** @description 403 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail-Forbidden"];
                };
            };
        };
    };
    "problem-box-create": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 워크스페이스 ID */
                workspaceId: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json;charset=UTF-8": components["schemas"]["CreateProblemBoxRequest"];
            };
        };
        responses: {
            /** @description 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse-ProblemBoxResponse"];
                };
            };
            /** @description 400 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail-Validation"];
                };
            };
            /** @description 403 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail-Forbidden"];
                };
            };
        };
    };
    "workspace-settings": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 워크스페이스 ID */
                workspaceId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse-WorkspaceSettings"];
                };
            };
            /** @description 403 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail-Forbidden"];
                };
            };
        };
    };
    "user-create-profile-image-presigned-url": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json;charset=UTF-8": components["schemas"]["ProfileImageUploadRequest"];
            };
        };
        responses: {
            /** @description 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse-PresignedUrlResponse"];
                };
            };
        };
    };
    "board-get": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 워크스페이스 ID */
                workspaceId: string;
                /** @description 게시글 ID */
                boardId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse-BoardDetail"];
                };
            };
        };
    };
    "board-delete": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 워크스페이스 ID */
                workspaceId: string;
                /** @description 게시글 ID */
                boardId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse-Void"];
                };
            };
        };
    };
    "board-update": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 워크스페이스 ID */
                workspaceId: string;
                /** @description 게시글 ID */
                boardId: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json;charset=UTF-8": components["schemas"]["UpdateBoardRequest"];
            };
        };
        responses: {
            /** @description 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse-BoardDetail"];
                };
            };
        };
    };
    "workspace-invite": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 워크스페이스 ID */
                workspaceId: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json;charset=UTF-8": components["schemas"]["InviteWorkspaceMemberRequest"];
            };
        };
        responses: {
            /** @description 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse-Void"];
                };
            };
            /** @description 400 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail-Validation"];
                };
            };
        };
    };
    "workspace-member-me": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 워크스페이스 ID */
                workspaceId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse-WorkspaceMemberResponse"];
                };
            };
            /** @description 403 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail-Forbidden"];
                };
            };
        };
    };
    "workspace-leave": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 워크스페이스 ID */
                workspaceId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse-Void"];
                };
            };
            /** @description 403 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail-Forbidden"];
                };
            };
        };
    };
    "workspace-member-remove": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 워크스페이스 ID */
                workspaceId: string;
                /** @description 워크스페이스 멤버 ID */
                workspaceMemberId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse-Void"];
                };
            };
            /** @description 403 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail-Forbidden"];
                };
            };
        };
    };
    "problem-box-get": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 워크스페이스 ID */
                workspaceId: string;
                /** @description 문제집 ID */
                problemBoxId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse-ProblemBoxResponse"];
                };
            };
            /** @description 404 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail-NotFound"];
                };
            };
        };
    };
    "problem-box-delete": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 워크스페이스 ID */
                workspaceId: string;
                /** @description 문제집 ID */
                problemBoxId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse-Void"];
                };
            };
            /** @description 403 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail-Forbidden"];
                };
            };
        };
    };
    "problem-box-update": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 워크스페이스 ID */
                workspaceId: string;
                /** @description 문제집 ID */
                problemBoxId: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json;charset=UTF-8": components["schemas"]["UpdateProblemBoxRequest"];
            };
        };
        responses: {
            /** @description 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse-ProblemBoxResponse"];
                };
            };
            /** @description 400 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail-Validation"];
                };
            };
        };
    };
    "board-comment-list": {
        parameters: {
            query?: {
                /** @description 페이지 */
                page?: string;
                /** @description 크기 */
                size?: string;
            };
            header?: never;
            path: {
                /** @description 워크스페이스 ID */
                workspaceId: string;
                /** @description 게시글 ID */
                boardId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse-CommentList"];
                };
            };
        };
    };
    "board-comment-create": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 워크스페이스 ID */
                workspaceId: string;
                /** @description 게시글 ID */
                boardId: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json;charset=UTF-8": components["schemas"]["CreateCommentRequest"];
            };
        };
        responses: {
            /** @description 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse-Comment"];
                };
            };
        };
    };
    "board-like-status": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 워크스페이스 ID */
                workspaceId: string;
                /** @description 게시글 ID */
                boardId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse-BoardLikeStatus"];
                };
            };
        };
    };
    "board-like": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 워크스페이스 ID */
                workspaceId: string;
                /** @description 게시글 ID */
                boardId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse-Void"];
                };
            };
        };
    };
    "board-unlike": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 워크스페이스 ID */
                workspaceId: string;
                /** @description 게시글 ID */
                boardId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse-Void"];
                };
            };
        };
    };
    "board-pin": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 워크스페이스 ID */
                workspaceId: string;
                /** @description 게시글 ID */
                boardId: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json;charset=UTF-8": components["schemas"]["PinBoardRequest"];
            };
        };
        responses: {
            /** @description 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse-Void"];
                };
            };
        };
    };
    "workspace-member-nickname-update": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 워크스페이스 ID */
                workspaceId: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json;charset=UTF-8": components["schemas"]["UpdateWorkspaceMemberNicknameRequest"];
            };
        };
        responses: {
            /** @description 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse-WorkspaceMemberResponse"];
                };
            };
            /** @description 400 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail-Validation"];
                };
            };
        };
    };
    "workspace-member-role-update": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 워크스페이스 ID */
                workspaceId: string;
                /** @description 워크스페이스 멤버 ID */
                workspaceMemberId: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json;charset=UTF-8": components["schemas"]["UpdateWorkspaceMemberRoleRequest"];
            };
        };
        responses: {
            /** @description 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse-Void"];
                };
            };
            /** @description 400 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail-Validation"];
                };
            };
        };
    };
    "board-comment-delete": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 워크스페이스 ID */
                workspaceId: string;
                /** @description 게시글 ID */
                boardId: string;
                /** @description 댓글 ID */
                commentId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse-Void"];
                };
            };
        };
    };
}
