/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/signup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 회원가입 */
        post: operations["auth-signup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 로그인 */
        post: operations["auth-login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 토큰 갱신 */
        post: operations["auth-refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 로그아웃 */
        post: operations["auth-logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 내 정보 조회
         * @description 로그인한 사용자의 정보를 조회합니다
         */
        get: operations["user-get-me"];
        put?: never;
        post?: never;
        /**
         * 회원 탈퇴
         * @description 로그인한 사용자의 계정을 삭제합니다
         */
        delete: operations["user-delete-me"];
        options?: never;
        head?: never;
        /**
         * 내 정보 수정
         * @description 로그인한 사용자의 정보를 수정합니다
         */
        patch: operations["user-update-me"];
        trace?: never;
    };
    "/api/v1/workspaces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 내 워크스페이스 목록 조회 */
        get: operations["workspace-list"];
        put?: never;
        /** 워크스페이스 생성 */
        post: operations["workspace-create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/explore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 워크스페이스 탐색 (공개) */
        get: operations["workspace-explore"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 워크스페이스 검색 */
        get: operations["workspace-search"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspaceId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 워크스페이스 상세 조회 */
        get: operations["workspace-get"];
        put?: never;
        post?: never;
        /** 워크스페이스 삭제 */
        delete: operations["workspace-delete"];
        options?: never;
        head?: never;
        /** 워크스페이스 수정 */
        patch: operations["workspace-update"];
        trace?: never;
    };
    "/api/v1/workspaces/{workspaceId}/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 워크스페이스 설정 조회 */
        get: operations["workspace-get-settings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspaceId}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 워크스페이스 멤버 목록 조회 */
        get: operations["workspace-member-list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspaceId}/members/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 워크스페이스 내 멤버 정보 조회 */
        get: operations["workspace-member-get-me"];
        put?: never;
        post?: never;
        /** 워크스페이스 탈퇴 */
        delete: operations["workspace-member-leave"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspaceId}/members/me/nickname": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** 워크스페이스 닉네임 변경 */
        patch: operations["workspace-member-update-nickname"];
        trace?: never;
    };
    "/api/v1/workspaces/{workspaceId}/members/invite": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 워크스페이스 멤버 초대 */
        post: operations["workspace-member-invite"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspaceId}/members/{workspaceMemberId}/role": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** 멤버 역할 변경 */
        patch: operations["workspace-member-update-role"];
        trace?: never;
    };
    "/api/v1/workspaces/{workspaceId}/members/{workspaceMemberId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** 멤버 강퇴 */
        delete: operations["workspace-member-remove"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspaceId}/boards": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 게시글 목록 조회 */
        get: operations["board-list"];
        put?: never;
        /** 게시글 작성 */
        post: operations["board-create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspaceId}/boards/{boardId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 게시글 상세 조회 */
        get: operations["board-get"];
        put?: never;
        post?: never;
        /** 게시글 삭제 */
        delete: operations["board-delete"];
        options?: never;
        head?: never;
        /** 게시글 수정 */
        patch: operations["board-update"];
        trace?: never;
    };
    "/api/v1/workspaces/{workspaceId}/boards/{boardId}/pin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** 게시글 고정/해제 */
        patch: operations["board-pin"];
        trace?: never;
    };
    "/api/v1/workspaces/{workspaceId}/boards/{boardId}/likes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 게시글 추천 상태 조회 */
        get: operations["board-like-status"];
        /** 게시글 추천 */
        put: operations["board-like"];
        post?: never;
        /** 게시글 추천 취소 */
        delete: operations["board-unlike"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspaceId}/boards/{boardId}/comments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 댓글 목록 조회 */
        get: operations["board-comment-list"];
        put?: never;
        /** 댓글 작성 */
        post: operations["board-comment-create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspaceId}/boards/{boardId}/comments/{commentId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** 댓글 삭제 */
        delete: operations["board-comment-delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/problems/{problemId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 문제 조회 (ID) */
        get: operations["problem-get-by-id"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/problems/number/{problemNumber}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 문제 조회 (백준 번호) */
        get: operations["problem-get-by-number"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/problems/ingest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 문제 수집 (익스텐션) */
        post: operations["problem-ingest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/submissions/{submissionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 제출 조회 */
        get: operations["submission-get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/submissions/ingest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 제출 수집 (익스텐션) */
        post: operations["submission-ingest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ApiResponseAuthTokenResponse: {
            success?: boolean;
            data?: components["schemas"]["AuthTokenResponse"];
            message?: string | null;
        };
        ApiResponseUserResponse: {
            success?: boolean;
            data?: components["schemas"]["UserResponse"];
            message?: string | null;
        };
        ApiResponseWorkspaceResponse: {
            success?: boolean;
            data?: components["schemas"]["WorkspaceResponse"];
            message?: string | null;
        };
        ApiResponseWorkspaceListResponse: {
            success?: boolean;
            data?: components["schemas"]["WorkspaceListResponse"];
            message?: string | null;
        };
        ApiResponseWorkspaceSettingsResponse: {
            success?: boolean;
            data?: components["schemas"]["WorkspaceSettingsResponse"];
            message?: string | null;
        };
        ApiResponseWorkspaceMemberResponse: {
            success?: boolean;
            data?: components["schemas"]["WorkspaceMemberResponse"];
            message?: string | null;
        };
        ApiResponseWorkspaceMemberListResponse: {
            success?: boolean;
            data?: components["schemas"]["WorkspaceMemberListResponse"];
            message?: string | null;
        };
        ApiResponsePageResponseWorkspaceResponse: {
            success?: boolean;
            data?: components["schemas"]["PageResponseWorkspaceResponse"];
            message?: string | null;
        };
        ApiResponseProblemResponse: {
            success?: boolean;
            data?: components["schemas"]["ProblemResponse"];
            message?: string | null;
        };
        ApiResponseSubmissionResponse: {
            success?: boolean;
            data?: components["schemas"]["SubmissionResponse"];
            message?: string | null;
        };
        ApiResponseBoardListResponse: {
            success?: boolean;
            data?: components["schemas"]["BoardListResponse"];
            message?: string | null;
        };
        ApiResponseBoardDetailResponse: {
            success?: boolean;
            data?: components["schemas"]["BoardDetailResponse"];
            message?: string | null;
        };
        ApiResponseBoardLikeStatusResponse: {
            success?: boolean;
            data?: components["schemas"]["BoardLikeStatusResponse"];
            message?: string | null;
        };
        ApiResponseCommentListResponse: {
            success?: boolean;
            data?: components["schemas"]["CommentListResponse"];
            message?: string | null;
        };
        ApiResponseCommentResponse: {
            success?: boolean;
            data?: components["schemas"]["CommentResponse"];
            message?: string | null;
        };
        SignupRequest: {
            /** Format: email */
            email: string;
            password: string;
            name: string;
        };
        LoginRequest: {
            email: string;
            password: string;
        };
        RefreshRequest: {
            refreshToken: string;
        };
        AuthTokenResponse: {
            accessToken?: string;
            refreshToken?: string;
        };
        UserResponse: {
            /** @description 유저 ID */
            id: number;
            /** @description 이메일 */
            email: string;
            /** @description 이름 */
            name: string;
            /** @description 프로필 이미지 URL */
            profileImageUrl?: string | null;
            /** @description 인증 제공자 (GOOGLE, KAKAO, LOCAL) */
            provider: string;
            /** @description 백준 아이디 */
            baekjoonId?: string | null;
        };
        UserUpdateRequest: {
            /** @description 수정할 이름 (30자 이내) */
            name?: string | null;
            /** @description 수정할 프로필 이미지 URL */
            profileImageUrl?: string | null;
            /** @description 백준 아이디 */
            baekjoonId?: string | null;
        };
        WorkspaceResponse: {
            /**
             * Format: int64
             * @description 워크스페이스 ID
             */
            id?: number;
            /** @description 워크스페이스 이름 */
            name?: string;
            /** @description 워크스페이스 설명 */
            description?: string | null;
        };
        WorkspaceListResponse: {
            items?: components["schemas"]["WorkspaceResponse"][];
        };
        WorkspaceSettingsResponse: {
            /** Format: int64 */
            id?: number;
            name?: string;
            description?: string | null;
            /** @description Mattermost Webhook URL */
            mmWebhookUrl?: string | null;
        };
        WorkspaceMemberResponse: {
            /**
             * Format: int64
             * @description 워크스페이스 멤버 ID
             */
            workspaceMemberId?: number;
            /** @description 워크스페이스 내 닉네임 */
            nickname?: string;
            /**
             * @description 멤버 역할 (OWNER, ADMIN, MEMBER)
             * @enum {string}
             */
            role?: "OWNER" | "ADMIN" | "MEMBER";
        };
        WorkspaceMemberListResponse: {
            items?: components["schemas"]["WorkspaceMemberResponse"][];
        };
        PageResponseWorkspaceResponse: {
            content?: components["schemas"]["WorkspaceResponse"][];
            page?: components["schemas"]["PageInfo"];
        };
        PageInfo: {
            page?: number;
            size?: number;
            /** Format: int64 */
            totalElements?: number;
            totalPages?: number;
        };
        CreateWorkspaceRequest: {
            /** @description 워크스페이스 이름 */
            name: string;
            /** @description 워크스페이스 설명 */
            description?: string | null;
        };
        UpdateWorkspaceRequest: {
            name?: string | null;
            description?: string | null;
            mmWebhookUrl?: string | null;
        };
        InviteWorkspaceMemberRequest: {
            /**
             * Format: email
             * @description 초대할 사용자 이메일
             */
            email: string;
        };
        UpdateWorkspaceMemberNicknameRequest: {
            /** @description 변경할 닉네임 */
            nickname: string;
        };
        UpdateWorkspaceMemberRoleRequest: {
            /**
             * @description 변경할 역할
             * @enum {string}
             */
            role: "OWNER" | "ADMIN" | "MEMBER";
        };
        ProblemResponse: {
            /** Format: int64 */
            id?: number;
            /** @description 백준 문제 번호 */
            problemNumber?: number;
            title?: string;
            tier?: string | null;
            timeLimit?: string | null;
            memoryLimit?: string | null;
            description?: string | null;
            inputDescription?: string | null;
            outputDescription?: string | null;
            url?: string | null;
            samples?: components["schemas"]["SampleResponse"][];
            algorithmTags?: components["schemas"]["AlgorithmTagResponse"][];
        };
        SampleResponse: {
            sampleIndex?: number;
            input?: string;
            output?: string;
        };
        AlgorithmTagResponse: {
            name?: string;
        };
        ProblemIngestRequest: {
            problemNum: number;
            title: string;
            tier?: string | null;
            timeLimit?: string | null;
            memoryLimit?: string | null;
            problemDesc?: string | null;
            problemInput?: string | null;
            problemOutput?: string | null;
            url?: string | null;
            samples?: components["schemas"]["SampleDto"][];
            tags?: components["schemas"]["TagDto"][];
        };
        SampleDto: {
            sampleIndex?: number;
            input?: string;
            output?: string;
        };
        TagDto: {
            name?: string;
        };
        SubmissionResponse: {
            /**
             * Format: int64
             * @description 제출 ID
             */
            id: number;
            /**
             * Format: int64
             * @description 백준 제출 ID
             */
            baekjoonSubmissionId: number;
            /** @description 백준 문제 번호 */
            problemNumber: number;
            /** @description 백준 사용자명 */
            username: string;
            /** @description 채점 결과 (맞았습니다!!, 틀렸습니다, 시간 초과 등) */
            verdict: string;
            /** @description 실행 시간 */
            executionTime?: string | null;
            /** @description 메모리 사용량 */
            memory?: string | null;
            /** @description 프로그래밍 언어 */
            language?: string | null;
            /** @description 코드 길이 */
            codeLength?: string | null;
        };
        SubmissionIngestRequest: {
            /**
             * Format: int64
             * @description 백준 제출 ID
             */
            submissionId: number;
            /** @description 백준 문제 번호 */
            problemNum: number;
            /** @description 백준 사용자명 */
            username: string;
            /** @description 채점 결과 */
            verdict: string;
            /** @description 실행 시간 */
            time?: string | null;
            /** @description 메모리 사용량 */
            memory?: string | null;
            /** @description 프로그래밍 언어 */
            language?: string | null;
            /** @description 코드 길이 */
            codeLength?: string | null;
            /** @description 소스 코드 */
            code?: string | null;
        };
        /**
         * @description 게시글 유형 (FREE=자유, NOTICE=공지, QNA=질문, DATA=자료)
         * @enum {string}
         */
        BoardType: "FREE" | "NOTICE" | "QNA" | "DATA";
        BoardAuthorResponse: {
            /**
             * Format: int64
             * @description 워크스페이스 멤버 ID
             */
            workspaceMemberId?: number;
            /** @description 닉네임 */
            nickname?: string;
        };
        BoardListItemResponse: {
            /**
             * Format: int64
             * @description 게시글 ID
             */
            boardId?: number;
            /**
             * Format: int64
             * @description 워크스페이스 ID
             */
            workspaceId?: number;
            type?: components["schemas"]["BoardType"];
            /** @description 상단 고정 여부 */
            pinned?: boolean;
            /** @description 게시글 제목 */
            title?: string;
            /** @description 본문 미리보기 */
            preview?: string;
            /**
             * Format: int64
             * @description 조회수
             */
            viewCount?: number;
            /**
             * Format: int64
             * @description 추천수
             */
            likeCount?: number;
            /**
             * Format: int64
             * @description 댓글수
             */
            commentCount?: number;
            /** @description 내 추천 여부 */
            myLike?: boolean;
            author?: components["schemas"]["BoardAuthorResponse"];
            /**
             * Format: date-time
             * @description 작성일시
             */
            createdAt?: string;
            /**
             * Format: date-time
             * @description 수정일시
             */
            updatedAt?: string;
        };
        BoardListResponse: {
            items?: components["schemas"]["BoardListItemResponse"][];
            page?: components["schemas"]["PageInfo"];
        };
        BoardDetailResponse: {
            /**
             * Format: int64
             * @description 게시글 ID
             */
            boardId?: number;
            /**
             * Format: int64
             * @description 워크스페이스 ID
             */
            workspaceId?: number;
            type?: components["schemas"]["BoardType"];
            /** @description 상단 고정 여부 */
            pinned?: boolean;
            /** @description 게시글 제목 */
            title?: string;
            /** @description 게시글 본문 (마크다운) */
            content?: string;
            /**
             * Format: int64
             * @description 조회수
             */
            viewCount?: number;
            /**
             * Format: int64
             * @description 추천수
             */
            likeCount?: number;
            /**
             * Format: int64
             * @description 댓글수
             */
            commentCount?: number;
            /** @description 내 추천 여부 */
            myLike?: boolean;
            author?: components["schemas"]["BoardAuthorResponse"];
            /**
             * Format: date-time
             * @description 작성일시
             */
            createdAt?: string;
            /**
             * Format: date-time
             * @description 수정일시
             */
            updatedAt?: string;
        };
        BoardLikeStatusResponse: {
            /**
             * Format: int64
             * @description 추천수
             */
            likeCount?: number;
            /** @description 내 추천 여부 */
            myLike?: boolean;
        };
        CreateBoardRequest: {
            type: components["schemas"]["BoardType"];
            /** @description 게시글 제목 */
            title: string;
            /** @description 게시글 본문 (마크다운) */
            content: string;
            /** @description 상단 고정 여부 */
            pinned?: boolean | null;
        };
        UpdateBoardRequest: {
            type?: components["schemas"]["BoardType"];
            title?: string | null;
            content?: string | null;
            pinned?: boolean | null;
        };
        PinBoardRequest: {
            /** @description 고정 여부 */
            pinned: boolean;
        };
        CommentResponse: {
            /**
             * Format: int64
             * @description 댓글 ID
             */
            boardCommentId?: number;
            /**
             * Format: int64
             * @description 게시글 ID
             */
            boardId?: number;
            /** @description 댓글 내용 */
            content?: string;
            author?: components["schemas"]["BoardAuthorResponse"];
            /**
             * Format: date-time
             * @description 작성일시
             */
            createdAt?: string;
        };
        CommentListResponse: {
            items?: components["schemas"]["CommentResponse"][];
            page?: components["schemas"]["PageInfo"];
        };
        CreateCommentRequest: {
            /** @description 댓글 내용 */
            content: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    "auth-signup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["SignupRequest"];
            };
        };
        responses: {
            /** @description 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseAuthTokenResponse"];
                };
            };
        };
    };
    "auth-login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseAuthTokenResponse"];
                };
            };
        };
    };
    "auth-refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseAuthTokenResponse"];
                };
            };
        };
    };
    "auth-logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "user-get-me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseUserResponse"];
                };
            };
        };
    };
    "user-delete-me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 204 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "user-update-me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["UserUpdateRequest"];
            };
        };
        responses: {
            /** @description 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseUserResponse"];
                };
            };
        };
    };
    "workspace-list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseWorkspaceListResponse"];
                };
            };
        };
    };
    "workspace-create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["CreateWorkspaceRequest"];
            };
        };
        responses: {
            /** @description 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseWorkspaceResponse"];
                };
            };
        };
    };
    "workspace-explore": {
        parameters: {
            query?: {
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponsePageResponseWorkspaceResponse"];
                };
            };
        };
    };
    "workspace-search": {
        parameters: {
            query: {
                name: string;
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponsePageResponseWorkspaceResponse"];
                };
            };
        };
    };
    "workspace-get": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseWorkspaceResponse"];
                };
            };
        };
    };
    "workspace-delete": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 204 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "workspace-update": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["UpdateWorkspaceRequest"];
            };
        };
        responses: {
            /** @description 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseWorkspaceResponse"];
                };
            };
        };
    };
    "workspace-get-settings": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseWorkspaceSettingsResponse"];
                };
            };
        };
    };
    "workspace-member-list": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseWorkspaceMemberListResponse"];
                };
            };
        };
    };
    "workspace-member-get-me": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseWorkspaceMemberResponse"];
                };
            };
        };
    };
    "workspace-member-leave": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 204 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "workspace-member-update-nickname": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["UpdateWorkspaceMemberNicknameRequest"];
            };
        };
        responses: {
            /** @description 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseWorkspaceMemberResponse"];
                };
            };
        };
    };
    "workspace-member-invite": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["InviteWorkspaceMemberRequest"];
            };
        };
        responses: {
            /** @description 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "workspace-member-update-role": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: number;
                workspaceMemberId: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["UpdateWorkspaceMemberRoleRequest"];
            };
        };
        responses: {
            /** @description 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "workspace-member-remove": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: number;
                workspaceMemberId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 204 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "board-list": {
        parameters: {
            query?: {
                type?: "FREE" | "NOTICE" | "QNA" | "DATA";
                keyword?: string;
                page?: number;
                size?: number;
                sort?: string;
                pinnedFirst?: boolean;
            };
            header?: never;
            path: {
                workspaceId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseBoardListResponse"];
                };
            };
        };
    };
    "board-create": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["CreateBoardRequest"];
            };
        };
        responses: {
            /** @description 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseBoardDetailResponse"];
                };
            };
        };
    };
    "board-get": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: number;
                boardId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseBoardDetailResponse"];
                };
            };
        };
    };
    "board-delete": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: number;
                boardId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 204 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "board-update": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: number;
                boardId: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["UpdateBoardRequest"];
            };
        };
        responses: {
            /** @description 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseBoardDetailResponse"];
                };
            };
        };
    };
    "board-pin": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: number;
                boardId: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PinBoardRequest"];
            };
        };
        responses: {
            /** @description 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "board-like-status": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: number;
                boardId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseBoardLikeStatusResponse"];
                };
            };
        };
    };
    "board-like": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: number;
                boardId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "board-unlike": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: number;
                boardId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "board-comment-list": {
        parameters: {
            query?: {
                page?: number;
                size?: number;
            };
            header?: never;
            path: {
                workspaceId: number;
                boardId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseCommentListResponse"];
                };
            };
        };
    };
    "board-comment-create": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: number;
                boardId: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["CreateCommentRequest"];
            };
        };
        responses: {
            /** @description 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseCommentResponse"];
                };
            };
        };
    };
    "board-comment-delete": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: number;
                boardId: number;
                commentId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 204 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "problem-get-by-id": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                problemId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseProblemResponse"];
                };
            };
        };
    };
    "problem-get-by-number": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                problemNumber: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseProblemResponse"];
                };
            };
        };
    };
    "problem-ingest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ProblemIngestRequest"];
            };
        };
        responses: {
            /** @description 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseProblemResponse"];
                };
            };
        };
    };
    "submission-get": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                submissionId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseSubmissionResponse"];
                };
            };
        };
    };
    "submission-ingest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["SubmissionIngestRequest"];
            };
        };
        responses: {
            /** @description 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseSubmissionResponse"];
                };
            };
        };
    };
}
